/**
 * Maps Answer Key "הסבר:" labels → category slug + distractor profile.
 */
export const LABEL_TO_CATEGORY = [
  [/present perfect.*never/i, 'present_perfect_never'],
  [/present perfect.*already/i, 'present_perfect_already'],
  [/present perfect.*yet/i, 'present_perfect_negative'],
  [/present perfect.*just/i, 'present_perfect_just'],
  [/present perfect.*since/i, 'present_perfect_since'],
  [/present perfect.*for/i, 'present_perfect_for'],
  [/present perfect.*how long/i, 'present_perfect_question'],
  [/present perfect(?!.*never|.*already|.*yet|.*just|.*since|.*for|.*how)/i, 'present_perfect'],
  [/past continuous.*שתי|past continuous.*simult/i, 'past_continuous_dual'],
  [/past continuous.*\+ past simple|past simple.*past continuous/i, 'past_continuous_mixed'],
  [/past continuous/i, 'past_continuous'],
  [/second conditional/i, 'second_conditional'],
  [/third conditional/i, 'third_conditional'],
  [/first conditional.*שליל|first conditional.*negative/i, 'first_conditional_negative'],
  [/first conditional/i, 'first_conditional'],
  [/past simple passive/i, 'past_passive'],
  [/present simple passive/i, 'present_passive'],
  [/passive/i, 'past_passive'],
  [/modal.*must/i, 'modal_must'],
  [/modal.*should/i, 'modal_should'],
  [/modal.*might/i, 'modal_might'],
  [/modal.*advice/i, 'modal_should'],
  [/modal/i, 'modal_must'],
  [/relative.*where/i, 'relative_where'],
  [/relative.*who/i, 'relative_who'],
  [/relative.*that/i, 'relative_that'],
  [/relative pronoun/i, 'relative_who'],
  [/will for prediction|future simple/i, 'future_will'],
  [/going to for prediction/i, 'going_to_prediction'],
  [/going to for plans|present continuous for future|present continuous.*עתיד/i, 'future_going_to'],
  [/present continuous.*שליל.*עתיד|present continuous negative/i, 'am_not_going'],
  [/superlative.*the|superlative עם the/i, 'superlative_the'],
  [/superlative/i, 'superlative'],
  [/gerund after.*good at|gerund.*good at/i, 'gerund_good_at'],
  [/gerund after.*hate|gerund.*hate/i, 'gerund_after_hate'],
  [/gerund after.*interested|gerund.*interested/i, 'gerund_interested'],
  [/gerund after.*stop|gerund.*stop/i, 'gerund_stop'],
  [/gerund/i, 'gerund_after_hate'],
  [/infinitive after.*promise|infinitive.*promise/i, 'infinitive_promise'],
  [/infinitive of purpose|expressing purpose/i, 'infinitive_purpose'],
  [/infinitive/i, 'infinitive_purpose'],
  [/prepositions of place and time|prepositions.*place.*time/i, 'prepositions_dual'],
  [/preposition.*on.*floor|preposition "on"/i, 'preposition_on'],
  [/preposition.*by.*transport|preposition "by"/i, 'preposition_by'],
  [/prepositions of time.*in|prepositions.*month/i, 'preposition_in_time'],
  [/prepositions.*at.*airport|prepositions \(at/i, 'prepositions_at_on'],
  [/prepositions/i, 'preposition_in'],
  [/article before vowel|article "an"/i, 'article_an'],
  [/articles/i, 'article_an'],
  [/few with countable/i, 'quantifier_few'],
  [/many with countable|many עם/i, 'quantifier_many'],
  [/much.*uncountable|much עם/i, 'quantifier_much'],
  [/little.*uncountable|little עם/i, 'quantifier_little'],
  [/quantifier/i, 'quantifier_many'],
  [/adverb/i, 'adverb'],
  [/adjective/i, 'adjective'],
  [/present continuous(?!.*future)/i, 'present_continuous'],
  [/there were/i, 'there_were'],
  [/there are/i, 'there_are'],
  [/there is.*uncountable|there is \+/i, 'there_is'],
  [/there is.*are.*שאלה|there is \/ there are/i, 'there_question'],
  [/present simple.*habit|present simple - habit|present simple להרגל/i, 'present_simple_habit'],
  [/present simple.*always|present simple.*sometimes/i, 'present_simple_habit'],
  [/present simple.*שאלה|present simple בשאלה/i, 'present_simple_question'],
  [/present simple.*שליל|present simple negative|present simple שליל/i, 'present_simple_negative'],
  [/present simple(?!.*passive)/i, 'present_simple'],
  [/past simple.*שאלה.*שליל|past simple בשאלה שליל/i, 'past_simple_question_negative'],
  [/past simple.*when|past simple \(פעולה/i, 'past_simple'],
  [/past simple/i, 'past_simple'],
  [/comparative/i, 'comparative'],
  [/too =|too \/ enough|not.*enough/i, 'too_enough'],
  [/since \+/i, 'since'],
  [/for \+/i, 'for_duration'],
  [/so that/i, 'so_that'],
  [/reflexive/i, 'reflexive'],
  [/told \+/i, 'past_simple_told'],
  [/don.t have to/i, 'dont_have_to'],
]

export function labelToCategory(label) {
  const text = label.trim()
  for (const [re, slug] of LABEL_TO_CATEGORY) {
    if (re.test(text)) return slug
  }
  return 'general'
}

/** Distractor profile per category — pools of similar wrong answers */
export const DISTRACTOR_PROFILES = {
  preposition_in: ['on', 'at', 'by', 'for', 'to', 'from'],
  preposition_on: ['in', 'at', 'by', 'to', 'for', 'from'],
  preposition_by: ['in', 'on', 'at', 'with', 'for', 'to'],
  preposition_in_time: ['on', 'at', 'by', 'for', 'since', 'to'],
  prepositions_dual: ['in / in', 'on / on', 'at / at', 'by / by', 'for / for', 'to / to'],
  prepositions_at_on: ['at / on', 'in / on', 'on / at', 'at / in', 'in / at', 'by / on'],
  article_an: ['a', 'the', 'some', 'any', 'no', '—'],
  quantifier_few: ['little', 'many', 'much', 'a few', 'a little', 'some'],
  quantifier_many: ['much', 'few', 'little', 'a lot', 'some', 'any'],
  quantifier_much: ['many', 'few', 'little', 'a lot', 'some', 'any'],
  quantifier_little: ['few', 'much', 'many', 'a little', 'a few', 'some'],
  modal_should: ['must', 'might', 'can', 'have to', "don't have to", 'would'],
  modal_must: ['should', 'might', 'can', 'have to', "don't have to", 'would'],
  modal_might: ['must', 'should', 'can', 'will', 'would', 'may'],
  dont_have_to: ["don't have to", 'must', 'should', 'have to', "mustn't", 'need'],
  relative_who: ['which', 'that', 'where', 'when', 'whose', 'whom'],
  relative_where: ['which', 'that', 'who', 'when', 'whose', 'whom'],
  relative_that: ['who', 'which', 'where', 'when', 'whose', 'whom'],
  adverb: ['good', 'quick', 'slow', 'nice', 'bad', 'loud'],
  adjective: ['loudly', 'well', 'quickly', 'badly', 'nicely', 'slowly'],
  too_enough: ['too', 'enough', 'so', 'very', 'much', 'also'],
  since: ['for', 'from', 'since', 'in', 'at', 'by'],
  for_duration: ['since', 'for', 'from', 'in', 'at', 'by'],
  so_that: ['so that', 'because', 'to', 'in order to', 'so', 'that'],
  reflexive: ['myself', 'yourself', 'himself', 'herself', 'itself', 'themselves'],
  there_were: ['was', 'are', 'is', 'have been', 'had been', 'be'],
  there_are: ['is', 'was', 'were', 'have been', 'be', 'am'],
  there_is: ['are', 'was', 'were', 'have been', 'be', 'is'],
  there_question: ['Is there', 'Are there', 'Was there', 'Were there', 'There is', 'There are'],
  infinitive_purpose: ['to', 'for', 'in order to', 'so that', 'because', 'and'],
  superlative_the: ['the', 'a', 'an', 'most', 'more', 'best'],
  past_passive: ['is made', 'were made', 'was make', 'is built', 'was sent', 'has been made'],
  present_passive: ['was served', 'is serve', 'are served', 'was spoken', 'is speaks', 'were served'],
  present_continuous: ['is running', 'are running', 'was running', 'runs', 'run', 'running'],
  future_going_to: ['is going', 'are going', 'was going', 'goes', 'will go', 'went'],
  going_to_prediction: ['will rain', 'is raining', 'was going', 'rains', 'rained', 'going to rain'],
  infinitive_promise: ['to help', 'help', 'helping', 'helped', 'helps', 'for help'],
  present_perfect_already: ['have already finished', 'has already finished', 'has finished', 'had already finished', 'has already finish', 'already finished'],
  present_perfect_negative: ['have not seen', 'has not seen', 'have seen', 'had not seen', 'have not see', 'did not see'],
  present_perfect_for: ['have lived', 'has lived', 'had lived', 'have live', 'have living', 'lived'],
  going_to_visit: ['am going to visit', 'will visit', 'visited', 'is going to visit', 'go to visit', 'visiting'],
  am_not_going: ['am not going', 'is not going', 'are not going', 'was not going', 'will not go', 'not going'],
  present_simple_negative: ["don't like", "doesn't like", "didn't like", 'not like', "don't eat", "doesn't eat"],
  present_simple_habit: ['eat', 'eats', 'eating', 'ate', "don't eat", "doesn't eat"],
  present_simple: ['go', 'goes', 'going', 'went', 'work', 'works', 'working'],
  comparative: ['more expensive', 'expensive', 'most expensive', 'expensiver', 'less expensive', 'more cheap'],
  superlative: ['best', 'good', 'better', 'worst', 'bad', 'worse'],
}
